
[[main]]
  identifier = "about"
  name = "About"
  url = "about"
  weight = 1

[[main]]
  identifier = "posts"
  name = "Posts"
  url = "posts"
  weight = 2

[[main]]
  identifier = "GitHub"
  name = "GitHub"
  url = "https://github.com/yubikku"
  weight = 3