baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Jovic Gutierrez'
theme = "basic"

# Aggressively minify the final output
[minify]
  disableHTML = false
  disableCSS = false
  disableJS = false
  minifyOutput = true